# Generated by Django 3.2.6 on 2022-03-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_empdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='API.employee'),
        ),
    ]
