# Generated by Django 3.2.6 on 2022-03-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_empdetails_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
